name: Release Post Process
on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Post Process New Release
      run: |
        pip3 install github3.py
        python3 ./tmp/release_post_processing.py
